### ISSUE TITLE
What was it like to learn Scheme?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/scheme#136]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning Scheme? What was helpful while learning Scheme? What did you struggle with? How did you tackle problems?
1. In what ways did Scheme differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning Scheme :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by jitwit** [comment]
Scheme first caught my eye after I stumbled upon the SICP video lectures. After watching a few, I decided pick up a copy of the _Structure and Interpretation of Computer Programs_ and have been hooked since! 

I was previously a haskeller to the core, but I've become totally seduced by the flexibility and simplicity of scheme. The feeling that whenever I approach a new problem I get to work from a blank canvas is what I find especially wonderful about scheme as a means of expression.

To answer some of the specific questions: 
* SICP was helpful for general computational thinking, but not so much for learning specifics of the language. Dybvig's _The Scheme Programming Language_ has been most helpful for the latter.
* Biggest shift for me was moving away from static typing and (default) laziness.
* Prefix notation was weird at first, but I no longer understand why people prefer infix!
* Some challenges were finding existing code to use for projects. I found myself rolling my own implementations much more often, which in the end has been a valuable experience.
* Some concepts I continue to struggle to understand well are continuations and macros. Some concepts that carried over nicely were the functional _ABC_s.

**Comment by jitwit** [comment]
One small thing I'll add: `ChezScheme` in particular is a ridiculously fun compiler to use. It produces rather fast code, yet what gets me is that the compile times are lightening fast. The tight feedback loop that comes with it is a beautiful thing.
