### ISSUE TITLE
Acronym exercise fails with '0 test failures'

### ISSUE THREAD

**Issue by DHMike57** [exercism/scheme#252]
Solution works locally.  Also tried submitting the github example solution and got the same. Same applies to Roman Numerals. Perhaps it is to to with the srfi 64 tests?

**Comment by austinmlv** [comment]
I've had these same issues. It is indeed due to the srfi-64 tests. They don't output their results in the format that the test runner expects. I've submitted a [pull request](https://github.com/exercism/scheme/pull/253) with the srfi-64 tests rewritten using the custom test suite found in the other non-srfi-64 tests. Hopefully the exercism team will look it over and approve it.

**Comment by guygastineau** [comment]
Acronym should work if you upgrade the exercise through exercism after #262 gets merged.

**Comment by guygastineau** [comment]
Please upgrade and try again.
